import {type Dimension} from 'types/property';
import {type View} from 'types/view';

export const edge: Dimension = {
  left: 0, right: 0, top: 0, bottom: 0,
};

export const back: View = {
  style: {
    background: '#666',
  },
  dimension: edge,
};

export const back1: View = {
  style: {
    background: '#999',
  },
  dimension: edge,
};

export const whiteBack: View = {
  style: {
    background: '#fff',
  },
  dimension: edge,
};

export const spacer: View = {
  type: 'spacer',
};

export const numbers1 = [
  '0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0',
  '1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1',
  '2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2',
  '3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3',
  '4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4',
];

export const numbers = [
  '0 0 0 0 0',
  '1 1 1 1 1',
  '2 2 2 2 2',
  '3 3 3 3 3',
  '4 4 4 4 4',
];

export const texts1 = [
  '!journey of a thousand miles begi\nns with one step.\nThis ancient Chinese proverb rem\n\n\n\ninds us that even the longest and most difficult ventures have a starting point; it encourages taking the first step, no matter how daunting the task may seem.',
  'In the end, we will remember not the words \n\n\n\n\n\n\n\n\n\n\n\nof our enemies, but the silence of our friends.\nMartin Luther King Jr.\'s words emphasize the importance of standing up for what is right, even in the face of adversity. Silence, in the face of injustice, is a powerful action in itself.',
  'Do not dwell in the past, do not dre\nam of the future, concentrate the mind on the present moment.\nThis quote from Buddha teaches the value of mindfulness, the importance of focusing on the present rather than being caught up in regrets about the past or anxiety about the future.',
  'Education is the most powerful weapon which you can use to change the world.\nNelson Mandela\'s famous words highlight the transformative power of education. Through learning and knowledge, we have the ability to make a profound impact on society and shape a better future.',
  'The only way to do great work is to love what you do.\nSteve Jobs\' advice encourages us to pursue our passions and find joy in our work. When we love what we do, we are more likely to achieve excellence and find fulfillment.',
  'The only limit to our realization of tomorrow is our doubts of today.\nFranklin D. Roosevelt\'s words remind us that self-doubt can be our biggest obstacle. Belief in our potential and abilities is crucial for achieving our future goals.',
  'Happiness is not something ready made. It comes from your own actions.\nThis quote from the Dalai Lama emphasizes that happiness is a result of our own efforts and choices, rather than something that can be obtained externally or handed to us.',
  'Success is not final, failure is not fatal: It is the courage to continue that counts.\nWinston Churchill\'s quote underscores the importance of resilience. Success and failure are both part of life\'s journey, but it is the determination to keep going that truly matters.',
  'It is during our darkest moments that we must focus to see the light.\nAristotle Onassis\'s words highlight the power of hope and perseverance, even in times of great difficulty. By focusing on the positives, we can find our way out of the darkest situations.',
  'You miss 100% of the shots you don\'t take.\nThis quote, often \n\n\n\n\nattributed to Wayne Gretzky, serves as a powerful reminder of the importance of taking risks and seizing opportunities. Without taking action, there can be no progress or success!',
];

export const texts11 = [
  '[0] In the end, \n\n\n\nwe will remember not the words of our enemies, but the silence of our friends.\nMartin Luther King Jr.\'s words emphasize the importance of standing up for what is right, even in the face of adversity. Silence, in the face of injustice, is a powerful action in itself.',
  '[1] The journey of a thousand miles begins with one step.\nThis ancient Chinese proverb reminds us that even the longest and most difficult ventures have a starting point; it encourages taking the first step, no matter how daunting the task may seem.',
  '[2] In the end, \n\n\n\nwe will remember not the words of our enemies, but the silence of our friends.\nMartin Luther King Jr.\'s words emphasize the importance of standing up for what is right, even in the face of adversity. Silence, in the face of injustice, is a powerful action in itself.',
  '[3] Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.\nThis quote from Buddha teaches the value of mindfulness, the importance of focusing on the present rather than being caught up in regrets about the past or anxiety about the future.',
  '[4] Education is the most powerful weapon which you can use to change the world.\nNelson Mandela\'s famous words highlight the transformative power of education. Through learning and knowledge, we have the ability to make a profound impact on society and shape a better future.',
  '[5] The only way to do great work is to love what you do.\nSteve Jobs\' advice encourages us to pursue our passions and find joy in our work. When we love what we do, we are more likely to achieve excellence and find fulfillment.',
  '[6] The only limit to our realization of tomorrow is our doubts of today.\nFranklin D. Roosevelt\'s words remind us that self-doubt can be our biggest obstacle. Belief in our potential and abilities is crucial for achieving our future goals.',
  '[7] Happiness is not something ready made. It comes from your own actions.\nThis quote from the Dalai Lama emphasizes that happiness is a result of our own efforts and choices, rather than something that can be obtained externally or handed to us.',
  '[8] Success is not final, failure is not fatal: It is the courage to continue that counts.\nWinston Churchill\'s quote underscores the importance of resilience. Success and failure are both part of life\'s journey, but it is the determination to keep going that truly matters.',
  '[9] It is during our darkest moments that we must focus to see the light.\nAristotle Onassis\'s words highlight the power of hope and perseverance, even in times of great difficulty. By focusing on the positives, we can find our way out of the darkest situations.',
  '[10] The journey of a thousand miles begins with one step.\nThis ancient Chinese proverb reminds us that even the longest and most difficult ventures have a starting point; it encourages taking the first step, no matter how daunting the task may seem.',
];

export const texts = [
  '[0] - The journey of a thousand miles begins with one step.\nThis ancient Chinese proverb reminds us that even the longest and most difficult ventures have a starting point; it encourages taking the first step, no matter how daunting the task may seem.',
  '[1] In the end, \n\n\n\nwe will remember not the words of our enemies, but the silence of our friends.\nMartin Luther King Jr.\'s words emphasize the importance of standing up for what is right, even in the face of adversity. Silence, in the face of injustice, is a powerful action in itself.',
  '[2] In the end, \n\n\n\nwe will remember not the words of our enemies, but the silence of our friends.\nMartin Luther King Jr.\'s words emphasize the importance of standing up for what is right, even in the face of adversity. Silence, in the face of injustice, is a powerful action in itself.',
  '[3] Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.\nThis quote from Buddha teaches the value of mindfulness, the importance of focusing on the present rather than being caught up in regrets about the past or anxiety about the future.',
  '[4] Education is the most powerful weapon which you can use to change the world.\nNelson Mandela\'s famous words highlight the transformative power of education. Through learning and knowledge, we have the ability to make a profound impact on society and shape a better future.',
  '[5] The only way to do great work is to love what you do.\nSteve Jobs\' advice encourages us to pursue our passions and find joy in our work. When we love what we do, we are more likely to achieve excellence and find fulfillment.',
  '[6] The only limit to our realization of tomorrow is our doubts of today.\nFranklin D. Roosevelt\'s words remind us that self-doubt can be our biggest obstacle. Belief in our potential and abilities is crucial for achieving our future goals.',
  '[7] Happiness is not something ready made. It comes from your own actions.\nThis quote from the Dalai Lama emphasizes that happiness is a result of our own efforts and choices, rather than something that can be obtained externally or handed to us.',
  '[8] Success is not final, failure is not fatal: It is the courage to continue that counts.\nWinston Churchill\'s quote underscores the importance of resilience. Success and failure are both part of life\'s journey, but it is the determination to keep going that truly matters.',
  '[9] It is during our darkest moments that we must focus to see the light.\nAristotle Onassis\'s words highlight the power of hope and perseverance, even in times of great difficulty. By focusing on the positives, we can find our way out of the darkest situations.',
  '[10] You miss 100% of the shots you don\'t take.\nThis quote, often attributed to Wayne Gretzky, serves as a powerful reminder of the importance of taking risks and seizing opportunities. Without taking action, there can be no progress or success.',
  '[11] The journey of a thousand miles begins with one step.\nThis ancient Chinese proverb reminds us that even the longest and most difficult ventures have a starting point; it encourages taking the first step, no matter how daunting the task may seem.',
  '[12] In the end, \n\n\n\nwe will remember not the words of our enemies, but the silence of our friends.\nMartin Luther King Jr.\'s words emphasize the importance of standing up for what is right, even in the face of adversity. Silence, in the face of injustice, is a powerful action in itself.',
  '[13] Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.\nThis quote from Buddha teaches the value of mindfulness, the importance of focusing on the present rather than being caught up in regrets about the past or anxiety about the future.',
  '[14] Education is the most powerful weapon which you can use to change the world.\nNelson Mandela\'s famous words highlight the transformative power of education. Through learning and knowledge, we have the ability to make a profound impact on society and shape a better future.',
  '[15] The only way to do great work is to love what you do.\nSteve Jobs\' advice encourages us to pursue our passions and find joy in our work. When we love what we do, we are more likely to achieve excellence and find fulfillment.',
  '[16] The only limit to our realization of tomorrow is our doubts of today.\nFranklin D. Roosevelt\'s words remind us that self-doubt can be our biggest obstacle. Belief in our potential and abilities is crucial for achieving our future goals.',
  '[17] Happiness is not something ready made. It comes from your own actions.\nThis quote from the Dalai Lama emphasizes that happiness is a result of our own efforts and choices, rather than something that can be obtained externally or handed to us.',
  '[18] Success is not final, failure is not fatal: It is the courage to continue that counts.\nWinston Churchill\'s quote underscores the importance of resilience. Success and failure are both part of life\'s journey, but it is the determination to keep going that truly matters.',
  '[19] It is during our darkest moments that we must focus to see the light.\nAristotle Onassis\'s words highlight the power of hope and perseverance, even in times of great difficulty. By focusing on the positives, we can find our way out of the darkest situations.',
  '[20] You miss 100% of the shots you don\'t take.\nThis quote, often attributed to Wayne Gretzky, serves as a powerful reminder of the importance of taking risks and seizing opportunities. Without taking action, there can be no progress or success.',
  '[21] The journey of a thousand miles begins with one step.\nThis ancient Chinese proverb reminds us that even the longest and most difficult ventures have a starting point; it encourages taking the first step, no matter how daunting the task may seem.',
  '[22] In the end, \n\n\n\nwe will remember not the words of our enemies, but the silence of our friends.\nMartin Luther King Jr.\'s words emphasize the importance of standing up for what is right, even in the face of adversity. Silence, in the face of injustice, is a powerful action in itself.',
  '[23] Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.\nThis quote from Buddha teaches the value of mindfulness, the importance of focusing on the present rather than being caught up in regrets about the past or anxiety about the future.',
  '[24] Education is the most powerful weapon which you can use to change the world.\nNelson Mandela\'s famous words highlight the transformative power of education. Through learning and knowledge, we have the ability to make a profound impact on society and shape a better future.',
  '[25] The only way to do great work is to love what you do.\nSteve Jobs\' advice encourages us to pursue our passions and find joy in our work. When we love what we do, we are more likely to achieve excellence and find fulfillment.',
  '[26] The only limit to our realization of tomorrow is our doubts of today.\nFranklin D. Roosevelt\'s words remind us that self-doubt can be our biggest obstacle. Belief in our potential and abilities is crucial for achieving our future goals.',
  '[27] Happiness is not something ready made. It comes from your own actions.\nThis quote from the Dalai Lama emphasizes that happiness is a result of our own efforts and choices, rather than something that can be obtained externally or handed to us.',
  '[28] Success is not final, failure is not fatal: It is the courage to continue that counts.\nWinston Churchill\'s quote underscores the importance of resilience. Success and failure are both part of life\'s journey, but it is the determination to keep going that truly matters.',
  '[29] It is during our darkest moments that we must focus to see the light.\nAristotle Onassis\'s words highlight the power of hope and perseverance, even in times of great difficulty. By focusing on the positives, we can find our way out of the darkest situations.',
  '[30] You miss 100% of the shots you don\'t take.\nThis quote, often attributed to Wayne Gretzky, serves as a powerful reminder of the importance of taking risks and seizing opportunities. Without taking action, there can be no progress or success.',
  '[31] The journey of a thousand miles begins with one step.\nThis ancient Chinese proverb reminds us that even the longest and most difficult ventures have a starting point; it encourages taking the first step, no matter how daunting the task may seem.',
  '[32] In the end, \n\n\n\nwe will remember not the words of our enemies, but the silence of our friends.\nMartin Luther King Jr.\'s words emphasize the importance of standing up for what is right, even in the face of adversity. Silence, in the face of injustice, is a powerful action in itself.',
  '[33] Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.\nThis quote from Buddha teaches the value of mindfulness, the importance of focusing on the present rather than being caught up in regrets about the past or anxiety about the future.',
  '[34] Education is the most powerful weapon which you can use to change the world.\nNelson Mandela\'s famous words highlight the transformative power of education. Through learning and knowledge, we have the ability to make a profound impact on society and shape a better future.',
  '[35] The only way to do great work is to love what you do.\nSteve Jobs\' advice encourages us to pursue our passions and find joy in our work. When we love what we do, we are more likely to achieve excellence and find fulfillment.',
  '[36] The only limit to our realization of tomorrow is our doubts of today.\nFranklin D. Roosevelt\'s words remind us that self-doubt can be our biggest obstacle. Belief in our potential and abilities is crucial for achieving our future goals.',
  '[37] Happiness is not something ready made. It comes from your own actions.\nThis quote from the Dalai Lama emphasizes that happiness is a result of our own efforts and choices, rather than something that can be obtained externally or handed to us.',
  '[38] Success is not final, failure is not fatal: It is the courage to continue that counts.\nWinston Churchill\'s quote underscores the importance of resilience. Success and failure are both part of life\'s journey, but it is the determination to keep going that truly matters.',
  '[39] It is during our darkest moments that we must focus to see the light.\nAristotle Onassis\'s words highlight the power of hope and perseverance, even in times of great difficulty. By focusing on the positives, we can find our way out of the darkest situations.',
  '[40] You miss 100% of the shots you don\'t take.\nThis quote, often attributed to Wayne Gretzky, serves as a powerful reminder of the importance of taking risks and seizing opportunities. Without taking action, there can be no progress or success.',
  '[41] The journey of a thousand miles begins with one step.\nThis ancient Chinese proverb reminds us that even the longest and most difficult ventures have a starting point; it encourages taking the first step, no matter how daunting the task may seem.',
  '[42] In the end, \n\n\n\nwe will remember not the words of our enemies, but the silence of our friends.\nMartin Luther King Jr.\'s words emphasize the importance of standing up for what is right, even in the face of adversity. Silence, in the face of injustice, is a powerful action in itself.',
  '[43] Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.\nThis quote from Buddha teaches the value of mindfulness, the importance of focusing on the present rather than being caught up in regrets about the past or anxiety about the future.',
  '[44] Education is the most powerful weapon which you can use to change the world.\nNelson Mandela\'s famous words highlight the transformative power of education. Through learning and knowledge, we have the ability to make a profound impact on society and shape a better future.',
  '[45] The only way to do great work is to love what you do.\nSteve Jobs\' advice encourages us to pursue our passions and find joy in our work. When we love what we do, we are more likely to achieve excellence and find fulfillment.',
  '[46] The only limit to our realization of tomorrow is our doubts of today.\nFranklin D. Roosevelt\'s words remind us that self-doubt can be our biggest obstacle. Belief in our potential and abilities is crucial for achieving our future goals.',
  '[47] Happiness is not something ready made. It comes from your own actions.\nThis quote from the Dalai Lama emphasizes that happiness is a result of our own efforts and choices, rather than something that can be obtained externally or handed to us.',
  '[48] Success is not final, failure is not fatal: It is the courage to continue that counts.\nWinston Churchill\'s quote underscores the importance of resilience. Success and failure are both part of life\'s journey, but it is the determination to keep going that truly matters.',
  '[49] It is during our darkest moments that we must focus to see the light.\nAristotle Onassis\'s words highlight the power of hope and perseverance, even in times of great difficulty. By focusing on the positives, we can find our way out of the darkest situations.',
  '[50] You miss 100% of the shots you don\'t take.\nThis quote, often attributed to Wayne Gretzky, serves as a powerful reminder of the importance of taking risks and seizing opportunities. Without taking action, there can be no progress or success.',
  '[51] The journey of a thousand miles begins with one step.\nThis ancient Chinese proverb reminds us that even the longest and most difficult ventures have a starting point; it encourages taking the first step, no matter how daunting the task may seem.',
  '[52] In the end, \n\n\n\nwe will remember not the words of our enemies, but the silence of our friends.\nMartin Luther King Jr.\'s words emphasize the importance of standing up for what is right, even in the face of adversity. Silence, in the face of injustice, is a powerful action in itself.',
  '[53] Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.\nThis quote from Buddha teaches the value of mindfulness, the importance of focusing on the present rather than being caught up in regrets about the past or anxiety about the future.',
  '[54] Education is the most powerful weapon which you can use to change the world.\nNelson Mandela\'s famous words highlight the transformative power of education. Through learning and knowledge, we have the ability to make a profound impact on society and shape a better future.',
  '[55] The only way to do great work is to love what you do.\nSteve Jobs\' advice encourages us to pursue our passions and find joy in our work. When we love what we do, we are more likely to achieve excellence and find fulfillment.',
  '[56] The only limit to our realization of tomorrow is our doubts of today.\nFranklin D. Roosevelt\'s words remind us that self-doubt can be our biggest obstacle. Belief in our potential and abilities is crucial for achieving our future goals.',
  '[57] Happiness is not something ready made. It comes from your own actions.\nThis quote from the Dalai Lama emphasizes that happiness is a result of our own efforts and choices, rather than something that can be obtained externally or handed to us.',
  '[58] Success is not final, failure is not fatal: It is the courage to continue that counts.\nWinston Churchill\'s quote underscores the importance of resilience. Success and failure are both part of life\'s journey, but it is the determination to keep going that truly matters.',
  '[59] It is during our darkest moments that we must focus to see the light.\nAristotle Onassis\'s words highlight the power of hope and perseverance, even in times of great difficulty. By focusing on the positives, we can find our way out of the darkest situations.',
  '[60] You miss 100% of the shots you don\'t take.\nThis quote, often attributed to Wayne Gretzky, serves as a powerful reminder of the importance of taking risks and seizing opportunities. Without taking action, there can be no progress or success.',
  '[61] The journey of a thousand miles begins with one step.\nThis ancient Chinese proverb reminds us that even the longest and most difficult ventures have a starting point; it encourages taking the first step, no matter how daunting the task may seem.',
  '[62] In the end, \n\n\n\nwe will remember not the words of our enemies, but the silence of our friends.\nMartin Luther King Jr.\'s words emphasize the importance of standing up for what is right, even in the face of adversity. Silence, in the face of injustice, is a powerful action in itself.',
  '[63] Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.\nThis quote from Buddha teaches the value of mindfulness, the importance of focusing on the present rather than being caught up in regrets about the past or anxiety about the future.',
  '[64] Education is the most powerful weapon which you can use to change the world.\nNelson Mandela\'s famous words highlight the transformative power of education. Through learning and knowledge, we have the ability to make a profound impact on society and shape a better future.',
  '[65] The only way to do great work is to love what you do.\nSteve Jobs\' advice encourages us to pursue our passions and find joy in our work. When we love what we do, we are more likely to achieve excellence and find fulfillment.',
  '[66] The only limit to our realization of tomorrow is our doubts of today.\nFranklin D. Roosevelt\'s words remind us that self-doubt can be our biggest obstacle. Belief in our potential and abilities is crucial for achieving our future goals.',
  '[67] Happiness is not something ready made. It comes from your own actions.\nThis quote from the Dalai Lama emphasizes that happiness is a result of our own efforts and choices, rather than something that can be obtained externally or handed to us.',
  '[68] Success is not final, failure is not fatal: It is the courage to continue that counts.\nWinston Churchill\'s quote underscores the importance of resilience. Success and failure are both part of life\'s journey, but it is the determination to keep going that truly matters.',
  '[69] It is during our darkest moments that we must focus to see the light.\nAristotle Onassis\'s words highlight the power of hope and perseverance, even in times of great difficulty. By focusing on the positives, we can find our way out of the darkest situations.',
  '[70] You miss 100% of the shots you don\'t take.\nThis quote, often attributed to Wayne Gretzky, serves as a powerful reminder of the importance of taking risks and seizing opportunities. Without taking action, there can be no progress or success.',
  '[71] The journey of a thousand miles begins with one step.\nThis ancient Chinese proverb reminds us that even the longest and most difficult ventures have a starting point; it encourages taking the first step, no matter how daunting the task may seem.',
  '[72] In the end, \n\n\n\nwe will remember not the words of our enemies, but the silence of our friends.\nMartin Luther King Jr.\'s words emphasize the importance of standing up for what is right, even in the face of adversity. Silence, in the face of injustice, is a powerful action in itself.',
  '[73] Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.\nThis quote from Buddha teaches the value of mindfulness, the importance of focusing on the present rather than being caught up in regrets about the past or anxiety about the future.',
  '[74] Education is the most powerful weapon which you can use to change the world.\nNelson Mandela\'s famous words highlight the transformative power of education. Through learning and knowledge, we have the ability to make a profound impact on society and shape a better future.',
  '[75] The only way to do great work is to love what you do.\nSteve Jobs\' advice encourages us to pursue our passions and find joy in our work. When we love what we do, we are more likely to achieve excellence and find fulfillment.',
  '[76] The only limit to our realization of tomorrow is our doubts of today.\nFranklin D. Roosevelt\'s words remind us that self-doubt can be our biggest obstacle. Belief in our potential and abilities is crucial for achieving our future goals.',
  '[77] Happiness is not something ready made. It comes from your own actions.\nThis quote from the Dalai Lama emphasizes that happiness is a result of our own efforts and choices, rather than something that can be obtained externally or handed to us.',
  '[78] Success is not final, failure is not fatal: It is the courage to continue that counts.\nWinston Churchill\'s quote underscores the importance of resilience. Success and failure are both part of life\'s journey, but it is the determination to keep going that truly matters.',
  '[79] It is during our darkest moments that we must focus to see the light.\nAristotle Onassis\'s words highlight the power of hope and perseverance, even in times of great difficulty. By focusing on the positives, we can find our way out of the darkest situations.',
  '[80] You miss 100% of the shots you don\'t take.\nThis quote, often attributed to Wayne Gretzky, serves as a powerful reminder of the importance of taking risks and seizing opportunities. Without taking action, there can be no progress or success.',
  '[81] The journey of a thousand miles begins with one step.\nThis ancient Chinese proverb reminds us that even the longest and most difficult ventures have a starting point; it encourages taking the first step, no matter how daunting the task may seem.',
  '[82] In the end, \n\n\n\nwe will remember not the words of our enemies, but the silence of our friends.\nMartin Luther King Jr.\'s words emphasize the importance of standing up for what is right, even in the face of adversity. Silence, in the face of injustice, is a powerful action in itself.',
  '[83] Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.\nThis quote from Buddha teaches the value of mindfulness, the importance of focusing on the present rather than being caught up in regrets about the past or anxiety about the future.',
  '[84] Education is the most powerful weapon which you can use to change the world.\nNelson Mandela\'s famous words highlight the transformative power of education. Through learning and knowledge, we have the ability to make a profound impact on society and shape a better future.',
  '[85] The only way to do great work is to love what you do.\nSteve Jobs\' advice encourages us to pursue our passions and find joy in our work. When we love what we do, we are more likely to achieve excellence and find fulfillment.',
  '[86] The only limit to our realization of tomorrow is our doubts of today.\nFranklin D. Roosevelt\'s words remind us that self-doubt can be our biggest obstacle. Belief in our potential and abilities is crucial for achieving our future goals.',
  '[87] Happiness is not something ready made. It comes from your own actions.\nThis quote from the Dalai Lama emphasizes that happiness is a result of our own efforts and choices, rather than something that can be obtained externally or handed to us.',
  '[88] Success is not final, failure is not fatal: It is the courage to continue that counts.\nWinston Churchill\'s quote underscores the importance of resilience. Success and failure are both part of life\'s journey, but it is the determination to keep going that truly matters.',
  '[89] It is during our darkest moments that we must focus to see the light.\nAristotle Onassis\'s words highlight the power of hope and perseverance, even in times of great difficulty. By focusing on the positives, we can find our way out of the darkest situations.',
  '[90] You miss 100% of the shots you don\'t take.\nThis quote, often attributed to Wayne Gretzky, serves as a powerful reminder of the importance of taking risks and seizing opportunities. Without taking action, there can be no progress or success.',
  '[91] The journey of a thousand miles begins with one step.\nThis ancient Chinese proverb reminds us that even the longest and most difficult ventures have a starting point; it encourages taking the first step, no matter how daunting the task may seem.',
  '[92] In the end, \n\n\n\nwe will remember not the words of our enemies, but the silence of our friends.\nMartin Luther King Jr.\'s words emphasize the importance of standing up for what is right, even in the face of adversity. Silence, in the face of injustice, is a powerful action in itself.',
  '[93] Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.\nThis quote from Buddha teaches the value of mindfulness, the importance of focusing on the present rather than being caught up in regrets about the past or anxiety about the future.',
  '[94] Education is the most powerful weapon which you can use to change the world.\nNelson Mandela\'s famous words highlight the transformative power of education. Through learning and knowledge, we have the ability to make a profound impact on society and shape a better future.',
  '[95] The only way to do great work is to love what you do.\nSteve Jobs\' advice encourages us to pursue our passions and find joy in our work. When we love what we do, we are more likely to achieve excellence and find fulfillment.',
  '[96] The only limit to our realization of tomorrow is our doubts of today.\nFranklin D. Roosevelt\'s words remind us that self-doubt can be our biggest obstacle. Belief in our potential and abilities is crucial for achieving our future goals.',
  '[97] Happiness is not something ready made. It comes from your own actions.\nThis quote from the Dalai Lama emphasizes that happiness is a result of our own efforts and choices, rather than something that can be obtained externally or handed to us.',
  '[98] Success is not final, failure is not fatal: It is the courage to continue that counts.\nWinston Churchill\'s quote underscores the importance of resilience. Success and failure are both part of life\'s journey, but it is the determination to keep going that truly matters.',
  '[99] It is during our darkest moments that we must focus to see the light.\nAristotle Onassis\'s words highlight the power of hope and perseverance, even in times of great difficulty. By focusing on the positives, we can find our way out of the darkest situations.',
  '[100] You miss 100% of the shots you don\'t take.\nThis quote, often attributed to Wayne Gretzky, serves as a powerful reminder of the importance of taking risks and seizing opportunities. Without taking action, there can be no progress or success.',
  '[101] The journey of a thousand miles begins with one step.\nThis ancient Chinese proverb reminds us that even the longest and most difficult ventures have a starting point; it encourages taking the first step, no matter how daunting the task may seem.',
  '[102] In the end, \n\n\n\nwe will remember not the words of our enemies, but the silence of our friends.\nMartin Luther King Jr.\'s words emphasize the importance of standing up for what is right, even in the face of adversity. Silence, in the face of injustice, is a powerful action in itself.',
  '[103] Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.\nThis quote from Buddha teaches the value of mindfulness, the importance of focusing on the present rather than being caught up in regrets about the past or anxiety about the future.',
  '[104] Education is the most powerful weapon which you can use to change the world.\nNelson Mandela\'s famous words highlight the transformative power of education. Through learning and knowledge, we have the ability to make a profound impact on society and shape a better future.',
  '[105] The only way to do great work is to love what you do.\nSteve Jobs\' advice encourages us to pursue our passions and find joy in our work. When we love what we do, we are more likely to achieve excellence and find fulfillment.',
  '[106] The only limit to our realization of tomorrow is our doubts of today.\nFranklin D. Roosevelt\'s words remind us that self-doubt can be our biggest obstacle. Belief in our potential and abilities is crucial for achieving our future goals.',
  '[107] Happiness is not something ready made. It comes from your own actions.\nThis quote from the Dalai Lama emphasizes that happiness is a result of our own efforts and choices, rather than something that can be obtained externally or handed to us.',
  '[108] Success is not final, failure is not fatal: It is the courage to continue that counts.\nWinston Churchill\'s quote underscores the importance of resilience. Success and failure are both part of life\'s journey, but it is the determination to keep going that truly matters.',
  '[109] It is during our darkest moments that we must focus to see the light.\nAristotle Onassis\'s words highlight the power of hope and perseverance, even in times of great difficulty. By focusing on the positives, we can find our way out of the darkest situations.',
  '[110] You miss 100% of the shots you don\'t take.\nThis quote, often attributed to Wayne Gretzky, serves as a powerful reminder of the importance of taking risks and seizing opportunities. Without taking action, there can be no progress or success.',
  '[111] The journey of a thousand miles begins with one step.\nThis ancient Chinese proverb reminds us that even the longest and most difficult ventures have a starting point; it encourages taking the first step, no matter how daunting the task may seem.',
  '[112] In the end, \n\n\n\nwe will remember not the words of our enemies, but the silence of our friends.\nMartin Luther King Jr.\'s words emphasize the importance of standing up for what is right, even in the face of adversity. Silence, in the face of injustice, is a powerful action in itself.',
  '[113] Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.\nThis quote from Buddha teaches the value of mindfulness, the importance of focusing on the present rather than being caught up in regrets about the past or anxiety about the future.',
  '[114] Education is the most powerful weapon which you can use to change the world.\nNelson Mandela\'s famous words highlight the transformative power of education. Through learning and knowledge, we have the ability to make a profound impact on society and shape a better future.',
  '[115] The only way to do great work is to love what you do.\nSteve Jobs\' advice encourages us to pursue our passions and find joy in our work. When we love what we do, we are more likely to achieve excellence and find fulfillment.',
  '[116] The only limit to our realization of tomorrow is our doubts of today.\nFranklin D. Roosevelt\'s words remind us that self-doubt can be our biggest obstacle. Belief in our potential and abilities is crucial for achieving our future goals.',
  '[117] Happiness is not something ready made. It comes from your own actions.\nThis quote from the Dalai Lama emphasizes that happiness is a result of our own efforts and choices, rather than something that can be obtained externally or handed to us.',
  '[118] Success is not final, failure is not fatal: It is the courage to continue that counts.\nWinston Churchill\'s quote underscores the importance of resilience. Success and failure are both part of life\'s journey, but it is the determination to keep going that truly matters.',
  '[119] It is during our darkest moments that we must focus to see the light.\nAristotle Onassis\'s words highlight the power of hope and perseverance, even in times of great difficulty. By focusing on the positives, we can find our way out of the darkest situations.',
  '[120] You miss 100% of the shots you don\'t take.\nThis quote, often attributed to Wayne Gretzky, serves as a powerful reminder of the importance of taking risks and seizing opportunities. Without taking action, there can be no progress or success.',
  '[121] The journey of a thousand miles begins with one step.\nThis ancient Chinese proverb reminds us that even the longest and most difficult ventures have a starting point; it encourages taking the first step, no matter how daunting the task may seem.',
  '[122] In the end, \n\n\n\nwe will remember not the words of our enemies, but the silence of our friends.\nMartin Luther King Jr.\'s words emphasize the importance of standing up for what is right, even in the face of adversity. Silence, in the face of injustice, is a powerful action in itself.',
  '[123] Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.\nThis quote from Buddha teaches the value of mindfulness, the importance of focusing on the present rather than being caught up in regrets about the past or anxiety about the future.',
  '[124] Education is the most powerful weapon which you can use to change the world.\nNelson Mandela\'s famous words highlight the transformative power of education. Through learning and knowledge, we have the ability to make a profound impact on society and shape a better future.',
  '[125] The only way to do great work is to love what you do.\nSteve Jobs\' advice encourages us to pursue our passions and find joy in our work. When we love what we do, we are more likely to achieve excellence and find fulfillment.',
  '[126] The only limit to our realization of tomorrow is our doubts of today.\nFranklin D. Roosevelt\'s words remind us that self-doubt can be our biggest obstacle. Belief in our potential and abilities is crucial for achieving our future goals.',
  '[127] Happiness is not something ready made. It comes from your own actions.\nThis quote from the Dalai Lama emphasizes that happiness is a result of our own efforts and choices, rather than something that can be obtained externally or handed to us.',
  '[128] It is during our darkest moments that we must focus to see the light.\nAristotle Onassis\'s words highlight the power of hope and perseverance, even in times of great difficulty. By focusing on the positives, we can find our way out of the darkest situations.-',
];
